// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStoragePath() {
  return window['go']['main']['App']['GetStoragePath']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetScreenContrast(arg1, arg2) {
  return window['go']['main']['App']['GetScreenContrast'](arg1, arg2);
}

export function SaveHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveHistory'](arg1, arg2, arg3);
}

export function SetMiniWindowMode(arg1) {
  return window['go']['main']['App']['SetMiniWindowMode'](arg1);
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}
